language: java
jdk: openjdk8
services:
  - docker
addons:
sonarcloud:
  organization: "AndreaPuccia"
  token:
    secure: $SONAR_TOKEN
install: skip
cache:
  directories:
    - $HOME/.m2
script:
  - mvn -f pom.xml clean verify coveralls:report sonar:sonar